[variables]
NIXPACKS_NODE_VERSION = "23"

[phases.setup]
nixPkgs = ["nodejs_23", "git-lfs"]

[phases.install]
cmds = [
  "if [ -d .git ]; then git lfs install --local && git lfs pull; fi",
  "rm -rf node_modules",
  "npm ci --legacy-peer-deps"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .output/server/index.mjs"
